#!/bin/sh

QEMU_DEFCONFIG=configs/qemu_aarch64_virt_defconfig
MODIFIED_QEMU_DEFCONFIG=base_external/configs/_qemu_defconfig
GATEWAY_DEFAULT_DEFCONFIG=${QEMU_DEFCONFIG}
GATEWAY_MODIFIED_DEFCONFIG=${MODIFIED_QEMU_DEFCONFIG}
GATEWAY_MODIFIED_DEFCONFIG_REL_BUILDROOT=../${GATEWAY_MODIFIED_DEFCONFIG}
